integer_var = 5
float_var = 0.12
string_var = "Hello Pythen"
list_var = [2, 3, 4, 6, 8, 12]
tuple_var = (2, 4, 56)
dict_var = {"name": "Djon", "age": 19}
set_var = {1, 2, 3, 4, 5, 6, 7}
bool_var = True
print('integer_var = ', integer_var )
print('float_var = ', float_var )
print('string_var = ', string_var )
print('list_var = ', list_var )
print('tuple_var = ', tuple_var )
print('dict_var = ', dict_var )
print('set_var = ', set_var )
print('bool_var = ', bool_var )
